/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as HrRouteImport } from './routes/hr'
import { Route as EnRouteImport } from './routes/en'
import { Route as DeRouteImport } from './routes/de'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HrIndexRouteImport } from './routes/hr/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as DeIndexRouteImport } from './routes/de/index'
import { Route as HrPricingRouteImport } from './routes/hr/pricing'
import { Route as HrCartRouteImport } from './routes/hr/cart'
import { Route as EnPricingRouteImport } from './routes/en/pricing'
import { Route as EnCartRouteImport } from './routes/en/cart'
import { Route as DePricingRouteImport } from './routes/de/pricing'
import { Route as DeCartRouteImport } from './routes/de/cart'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const DeRoute = DeRouteImport.update({
  id: '/de',
  path: '/de',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HrIndexRoute = HrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HrRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const DeIndexRoute = DeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeRoute,
} as any)
const HrPricingRoute = HrPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => HrRoute,
} as any)
const HrCartRoute = HrCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => HrRoute,
} as any)
const EnPricingRoute = EnPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => EnRoute,
} as any)
const EnCartRoute = EnCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => EnRoute,
} as any)
const DePricingRoute = DePricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => DeRoute,
} as any)
const DeCartRoute = DeCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => DeRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/cart': typeof CartRoute
  '/datenschutz': typeof DatenschutzRoute
  '/de': typeof DeRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/hr': typeof HrRouteWithChildren
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/de/cart': typeof DeCartRoute
  '/de/pricing': typeof DePricingRoute
  '/en/cart': typeof EnCartRoute
  '/en/pricing': typeof EnPricingRoute
  '/hr/cart': typeof HrCartRoute
  '/hr/pricing': typeof HrPricingRoute
  '/de/': typeof DeIndexRoute
  '/en/': typeof EnIndexRoute
  '/hr/': typeof HrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/cart': typeof CartRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/de/cart': typeof DeCartRoute
  '/de/pricing': typeof DePricingRoute
  '/en/cart': typeof EnCartRoute
  '/en/pricing': typeof EnPricingRoute
  '/hr/cart': typeof HrCartRoute
  '/hr/pricing': typeof HrPricingRoute
  '/de': typeof DeIndexRoute
  '/en': typeof EnIndexRoute
  '/hr': typeof HrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/cart': typeof CartRoute
  '/datenschutz': typeof DatenschutzRoute
  '/de': typeof DeRouteWithChildren
  '/en': typeof EnRouteWithChildren
  '/hr': typeof HrRouteWithChildren
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/de/cart': typeof DeCartRoute
  '/de/pricing': typeof DePricingRoute
  '/en/cart': typeof EnCartRoute
  '/en/pricing': typeof EnPricingRoute
  '/hr/cart': typeof HrCartRoute
  '/hr/pricing': typeof HrPricingRoute
  '/de/': typeof DeIndexRoute
  '/en/': typeof EnIndexRoute
  '/hr/': typeof HrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/cart'
    | '/datenschutz'
    | '/de'
    | '/en'
    | '/hr'
    | '/impressum'
    | '/login'
    | '/pricing'
    | '/register'
    | '/checkout/success'
    | '/de/cart'
    | '/de/pricing'
    | '/en/cart'
    | '/en/pricing'
    | '/hr/cart'
    | '/hr/pricing'
    | '/de/'
    | '/en/'
    | '/hr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/cart'
    | '/datenschutz'
    | '/impressum'
    | '/login'
    | '/pricing'
    | '/register'
    | '/checkout/success'
    | '/de/cart'
    | '/de/pricing'
    | '/en/cart'
    | '/en/pricing'
    | '/hr/cart'
    | '/hr/pricing'
    | '/de'
    | '/en'
    | '/hr'
  id:
    | '__root__'
    | '/'
    | '/agb'
    | '/cart'
    | '/datenschutz'
    | '/de'
    | '/en'
    | '/hr'
    | '/impressum'
    | '/login'
    | '/pricing'
    | '/register'
    | '/checkout/success'
    | '/de/cart'
    | '/de/pricing'
    | '/en/cart'
    | '/en/pricing'
    | '/hr/cart'
    | '/hr/pricing'
    | '/de/'
    | '/en/'
    | '/hr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgbRoute: typeof AgbRoute
  CartRoute: typeof CartRoute
  DatenschutzRoute: typeof DatenschutzRoute
  DeRoute: typeof DeRouteWithChildren
  EnRoute: typeof EnRouteWithChildren
  HrRoute: typeof HrRouteWithChildren
  ImpressumRoute: typeof ImpressumRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de': {
      id: '/de'
      path: '/de'
      fullPath: '/de'
      preLoaderRoute: typeof DeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/': {
      id: '/hr/'
      path: '/'
      fullPath: '/hr/'
      preLoaderRoute: typeof HrIndexRouteImport
      parentRoute: typeof HrRoute
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/de/': {
      id: '/de/'
      path: '/'
      fullPath: '/de/'
      preLoaderRoute: typeof DeIndexRouteImport
      parentRoute: typeof DeRoute
    }
    '/hr/pricing': {
      id: '/hr/pricing'
      path: '/pricing'
      fullPath: '/hr/pricing'
      preLoaderRoute: typeof HrPricingRouteImport
      parentRoute: typeof HrRoute
    }
    '/hr/cart': {
      id: '/hr/cart'
      path: '/cart'
      fullPath: '/hr/cart'
      preLoaderRoute: typeof HrCartRouteImport
      parentRoute: typeof HrRoute
    }
    '/en/pricing': {
      id: '/en/pricing'
      path: '/pricing'
      fullPath: '/en/pricing'
      preLoaderRoute: typeof EnPricingRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/cart': {
      id: '/en/cart'
      path: '/cart'
      fullPath: '/en/cart'
      preLoaderRoute: typeof EnCartRouteImport
      parentRoute: typeof EnRoute
    }
    '/de/pricing': {
      id: '/de/pricing'
      path: '/pricing'
      fullPath: '/de/pricing'
      preLoaderRoute: typeof DePricingRouteImport
      parentRoute: typeof DeRoute
    }
    '/de/cart': {
      id: '/de/cart'
      path: '/cart'
      fullPath: '/de/cart'
      preLoaderRoute: typeof DeCartRouteImport
      parentRoute: typeof DeRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DeRouteChildren {
  DeCartRoute: typeof DeCartRoute
  DePricingRoute: typeof DePricingRoute
  DeIndexRoute: typeof DeIndexRoute
}

const DeRouteChildren: DeRouteChildren = {
  DeCartRoute: DeCartRoute,
  DePricingRoute: DePricingRoute,
  DeIndexRoute: DeIndexRoute,
}

const DeRouteWithChildren = DeRoute._addFileChildren(DeRouteChildren)

interface EnRouteChildren {
  EnCartRoute: typeof EnCartRoute
  EnPricingRoute: typeof EnPricingRoute
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnCartRoute: EnCartRoute,
  EnPricingRoute: EnPricingRoute,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

interface HrRouteChildren {
  HrCartRoute: typeof HrCartRoute
  HrPricingRoute: typeof HrPricingRoute
  HrIndexRoute: typeof HrIndexRoute
}

const HrRouteChildren: HrRouteChildren = {
  HrCartRoute: HrCartRoute,
  HrPricingRoute: HrPricingRoute,
  HrIndexRoute: HrIndexRoute,
}

const HrRouteWithChildren = HrRoute._addFileChildren(HrRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgbRoute: AgbRoute,
  CartRoute: CartRoute,
  DatenschutzRoute: DatenschutzRoute,
  DeRoute: DeRouteWithChildren,
  EnRoute: EnRouteWithChildren,
  HrRoute: HrRouteWithChildren,
  ImpressumRoute: ImpressumRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
